/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/hermanYohanes.glb')
  return (
    <group ref={group} {...props} dispose={null}>
       <pointLight
        intensity={0}
        position={[-2.085, 1.4, -3.678]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials['Material.003']}
        position={[-2.51, 0.46, -0.5]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.06, 0.06, 0.06]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials['Material.005']}
        position={[-2.55, 0.45, -0.52]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.01, 0.01, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials['Material.007']}
        position={[-2.55, 0.48, -0.5]}
        scale={[0.01, 0.01, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={materials['Material.006']}
        position={[-2.55, 0.44, -0.5]}
        scale={[0.01, 0.01, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={materials['Material.004']}
        position={[-2.55, 0.45, -0.48]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.01, 0.01, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube009.geometry}
        material={materials['Material.012']}
        position={[-2.55, 0.16, -0.52]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.01, 0.01, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube008.geometry}
        material={materials['Material.011']}
        position={[-2.55, 0.18, -0.5]}
        scale={[0.01, 0.01, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={materials['Material.010']}
        position={[-2.55, 0.15, -0.5]}
        scale={[0.01, 0.01, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={materials['Material.009']}
        position={[-2.55, 0.16, -0.48]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.01, 0.01, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={materials['Material.008']}
        position={[-2.51, 0.16, -0.5]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.06, 0.06, 0.06]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube013.geometry}
        material={materials['Material.017']}
        position={[2.56, 0.46, -0.52]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[0.01, 0.01, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube012.geometry}
        material={materials['Material.016']}
        position={[2.56, 0.44, -0.5]}
        rotation={[0, 0, -3.14]}
        scale={[0.01, 0.01, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube011.geometry}
        material={materials['Material.015']}
        position={[2.56, 0.47, -0.5]}
        rotation={[0, 0, -3.14]}
        scale={[0.01, 0.01, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube010.geometry}
        material={materials['Material.014']}
        position={[2.56, 0.46, -0.48]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[0.01, 0.01, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002.geometry}
        material={materials['Material.013']}
        position={[2.52, 0.46, -0.5]}
        rotation={[0, 0, 1.57]}
        scale={[0.06, 0.06, 0.06]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube017.geometry}
        material={materials['Material.022']}
        position={[2.56, 0.16, -0.48]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[0.01, 0.01, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube016.geometry}
        material={materials['Material.021']}
        position={[2.56, 0.17, -0.5]}
        rotation={[0, 0, -3.14]}
        scale={[0.01, 0.01, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube015.geometry}
        material={materials['Material.020']}
        position={[2.56, 0.14, -0.5]}
        rotation={[0, 0, -3.14]}
        scale={[0.01, 0.01, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube014.geometry}
        material={materials['Material.019']}
        position={[2.56, 0.16, -0.52]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[0.01, 0.01, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder003.geometry}
        material={materials['Material.018']}
        position={[2.52, 0.16, -0.5]}
        rotation={[0, 0, 1.57]}
        scale={[0.06, 0.06, 0.06]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube018.geometry}
        material={materials['Material.023']}
        position={[0, -0.01, 0.43]}
        scale={[0.27, 0, 0.08]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube019.geometry}
        material={materials['Material.028']}
        position={[-1.06, 0.27, 0.26]}
        scale={[0.33, 0.01, -0.18]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder008.geometry}
        material={materials['Material.029']}
        position={[-0.77, 0.13, 0.11]}
        scale={[0, 0.13, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder004.geometry}
        material={materials['Material.030']}
        position={[-0.75, 0.13, 0.11]}
        scale={[0, 0.13, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder005.geometry}
        material={materials['Material.031']}
        position={[-0.76, 0.22, 0.11]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0, -0.01, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder006.geometry}
        material={materials['Material.032']}
        position={[-0.76, 0.21, 0.11]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0, -0.01, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder009.geometry}
        material={materials['Material.034']}
        position={[-0.76, 0.1, 0.11]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0, -0.01, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder007.geometry}
        material={materials['Material.033']}
        position={[-0.76, 0.09, 0.11]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0, -0.01, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder015.geometry}
        material={materials['Material.040']}
        position={[-0.96, 0.13, 0.11]}
        scale={[0, 0.13, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder014.geometry}
        material={materials['Material.039']}
        position={[-0.97, 0.22, 0.11]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0, -0.01, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder013.geometry}
        material={materials['Material.038']}
        position={[-0.97, 0.21, 0.11]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0, -0.01, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder012.geometry}
        material={materials['Material.037']}
        position={[-0.97, 0.09, 0.11]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0, -0.01, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder011.geometry}
        material={materials['Material.036']}
        position={[-0.98, 0.13, 0.11]}
        scale={[0, 0.13, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder010.geometry}
        material={materials['Material.035']}
        position={[-0.97, 0.1, 0.11]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0, -0.01, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder021.geometry}
        material={materials['Material.046']}
        position={[-1.16, 0.1, 0.11]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0, -0.01, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder020.geometry}
        material={materials['Material.045']}
        position={[-1.17, 0.13, 0.11]}
        scale={[0, 0.13, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder019.geometry}
        material={materials['Material.044']}
        position={[-1.16, 0.09, 0.11]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0, -0.01, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder018.geometry}
        material={materials['Material.043']}
        position={[-1.16, 0.21, 0.11]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0, -0.01, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder017.geometry}
        material={materials['Material.042']}
        position={[-1.16, 0.22, 0.11]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0, -0.01, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder016.geometry}
        material={materials['Material.041']}
        position={[-1.15, 0.13, 0.11]}
        scale={[0, 0.13, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder027.geometry}
        material={materials['Material.052']}
        position={[-1.37, 0.13, 0.11]}
        scale={[0, 0.13, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder026.geometry}
        material={materials['Material.051']}
        position={[-1.38, 0.22, 0.11]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0, -0.01, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder025.geometry}
        material={materials['Material.050']}
        position={[-1.38, 0.21, 0.11]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0, -0.01, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder024.geometry}
        material={materials['Material.049']}
        position={[-1.38, 0.09, 0.11]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0, -0.01, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder023.geometry}
        material={materials['Material.048']}
        position={[-1.39, 0.13, 0.11]}
        scale={[0, 0.13, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder022.geometry}
        material={materials['Material.047']}
        position={[-1.38, 0.1, 0.11]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0, -0.01, 0.01]}
      />
      <group position={[3.11, 0.24, -0.14]} scale={[0.37, 0.21, 0.16]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_1.geometry}
          material={materials['Material.053']}
          onClick={(e) => console.log('clicks')}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_2.geometry}
          material={materials.bolong}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_3.geometry}
          material={materials['Abu"']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_4.geometry}
          material={materials.Jendela}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_5.geometry}
          material={materials.Kaca}
        />
      </group>
      <group position={[0.01, 0.27, -0.51]} scale={[0.77, 0.27, 0.2]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube010_1.geometry}
          material={materials.Body}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube010_2.geometry}
          material={materials.Bolong}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube010_3.geometry}
          material={materials.Tiang}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube010_4.geometry}
          material={materials.Pintudanjendela}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube010_5.geometry}
          material={materials.atapabu}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube010_6.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube010_7.geometry}
          material={materials.Dalam}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube010_8.geometry}
          material={materials.Bawah}
        />
      </group>
      <group position={[0.01, 0.27, -0.51]} scale={[-0.77, 0.27, 0.2]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_1.geometry}
          material={materials['Body.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_2.geometry}
          material={materials['Bolong.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_3.geometry}
          material={materials['Tiang.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_4.geometry}
          material={materials['Pintudanjendela.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_5.geometry}
          material={materials['atapabu.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_6.geometry}
          material={materials['Material.024']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_7.geometry}
          material={materials['Dalam.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_8.geometry}
          material={materials['Bawah.002']}
        />
      </group>
      <group
        position={[0.01, 0.27, -5.82]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-0.77, 0.27, 0.2]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube025_1.geometry}
          material={materials['Body.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube025_2.geometry}
          material={materials['Bolong.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube025_3.geometry}
          material={materials['Tiang.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube025_4.geometry}
          material={materials['Pintudanjendela.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube025_5.geometry}
          material={materials['atapabu.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube025_6.geometry}
          material={materials['Material.061']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube025_7.geometry}
          material={materials['Dalam.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube025_8.geometry}
          material={materials['Bawah.003']}
        />
      </group>
      <group position={[0.07, 0.77, -0.71]} scale={[-1.02, 0.09, 0.38]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube023_1.geometry}
          material={materials['Material.057']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube023_2.geometry}
          material={materials['Material.058']}
        />
      </group>
      <group
        position={[0.01, 0.27, -5.82]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.77, 0.27, 0.2]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube022_1.geometry}
          material={materials['Body.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube022_2.geometry}
          material={materials['Bolong.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube022_3.geometry}
          material={materials['Tiang.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube022_4.geometry}
          material={materials['Pintudanjendela.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube022_5.geometry}
          material={materials['atapabu.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube022_6.geometry}
          material={materials['Material.055']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube022_7.geometry}
          material={materials['Dalam.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube022_8.geometry}
          material={materials['Bawah.001']}
        />
      </group>
      <group
        position={[0.07, 0.77, -5.64]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-1.02, 0.09, 0.38]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube024_1.geometry}
          material={materials['Material.060']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube024_2.geometry}
          material={materials['Material.059']}
        />
      </group>
      <group position={[0.07, 0.77, -0.71]} scale={[1.02, 0.09, 0.38]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube021_1.geometry}
          material={materials['Material.027']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube021_2.geometry}
          material={materials['Material.026']}
        />
      </group>
      <group
        position={[0.07, 0.77, -5.64]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[1.02, 0.09, 0.38]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube026_1.geometry}
          material={materials['Material.064']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube026_2.geometry}
          material={materials['Material.063']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/hermanYohanes.glb')
